// Fonts
import { Poppins } from "next/font/google";

// Components
import Header from "./components/Header";

// Style
import "./globals.css";
import Footer from "./components/Footer";

// Fonts Variables
const poppins = Poppins({
  subsets: ["latin"],
  preload: true,
  weight: ["500", "700"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
